### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zoehanlu** [allenjack/SAE-NAD#2]
Excuse me, why did I run this error?
![image](https://user-images.githubusercontent.com/31984667/62694664-61365980-ba07-11e9-9244-1d73a2607e3f.png)

**Comment by allenjack** [comment]
Hi,
I guess you are using a new version of pytorch. You can try to set reduction='none'.

**Comment by Zoehanlu** [comment]
> Hi,
> I guess you are using a new version of pytorch. You can try to set reduction='none'.

thank you~
